name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.x

    - name: Test
      run: go test -v ./...

    - name: Install yq
      run: go install github.com/mikefarah/yq/v4@latest

    - name: Command line test
      run: ./test.sh
